---
- hosts: E31 
  remote_user: root
  tasks:
  - name: OpenRobertaUSB nach /usr/local/share/ entpacken
    unarchive:
    # src: ./data/OpenRobertaUSBLinux-3.1.0.tar.gz
    # dest: /usr/local/share/
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
    with_items:
     - src: "./data/OpenRobertaUSBLinux-3.1.0.tar.gz"
       dest: "/usr/local/share/"
  - name: Berechtigungen 755 korrekt setzen
    file:
      path: /usr/local/share/OpenRobertaUSB
      state: directory
      recurse: yes
      owner: root
      group: root
      mode: 0755
  - name: jar-Datei ausführbar machen
    file:
      path: /usr/local/share/OpenRobertaUSB/OpenRobertaUSB.jar
      state: touch
      mode: u=rwx,g=rx,o=rx
      #modification_time: "preserve"
      #access_time: "preserve"
  - name: Desktop-Starter-Datei kopieren
    copy:
      src: ./data/ORUSB.desktop
      dest: /usr/share/applications/
      owner: root
      group: root
      mode: 0644




