---
- hosts: INFacerWLAN
  remote_user: root
  tasks:
  - name: Kopiere sources.list Datei von lokal nach remote
    ansible.builtin.copy:
      src: data/etc/apt/sources.list
      dest: /etc/apt/sources.list
      owner: root
      group: root
      mode: 0644

  - name: Aktualisiere die Paketliste
    command: apt update

  - name: Installiere Filius
    apt:
      name: filius
      state: present

  - name: Überprüfe, ob Filius installiert ist
    command: dpkg -l | grep filius
    register: filius_installed
    ignore_errors: true

  - name: Bestätige die Installation von Filius
    debug:
      msg: "Filius wurde erfolgreich installiert."
    when: filius_installed.rc == 0

  - name: Fehlermeldung, wenn die Installation fehlgeschlagen ist
    debug:
      msg: "Filius wurde nicht installiert."
    when: filius_installed.rc != 0

