---
- name: Erzwinge die Energieeinstellungen in Cinnamon systemweit
  vars:
    target_group: "{{ target_group | default('INFacerWLAN') }}"
  hosts: "{{ target_group }}"
  remote_user: root
  gather_facts: yes
  tasks:
    - name: Überprüfen, ob die aktuelle logind.conf die richtigen Konfigurationen enthält
      command: grep -E 'HandlePowerKey=poweroff|HandleLidSwitch=ignore|HandleSuspendKey=ignore|HandleHibernateKey=ignore|IdleAction=ignore|PowerKeyIgnoreInhibited=no|LidSwitchIgnoreInhibited=no' /etc/systemd/logind.conf
      register: logind_conf_check
      failed_when: logind_conf_check.rc != 0
      changed_when: false

    - name: Überprüfen, ob die logind.conf vollständig korrekt ist
      set_fact:
        config_correct: "{{ logind_conf_check.stdout_lines | length == 7 }}"

    - name: Erstellen der minimalen logind.conf, wenn die Konfiguration nicht korrekt ist
      copy:
        dest: /etc/systemd/logind.conf
        content: |
          [Login]
          HandlePowerKey=poweroff
          HandleLidSwitch=ignore
          HandleSuspendKey=ignore
          HandleHibernateKey=ignore
          IdleAction=ignore
          PowerKeyIgnoreInhibited=no
          LidSwitchIgnoreInhibited=no
      register: logind_conf_update
      when: not config_correct

    - name: Überprüfen der dconf-Berechtigungen
      command: ls -altR /etc/dconf
      register: dconf_permissions

    - name: Setzen der Berechtigungen für die dconf-Datenbankdatei 00-power-settings
      command: chmod 644 /etc/dconf/db/local.d/00-power-settings
      when: dconf_permissions.stdout.find('00-power-settings') != -1

    - name: Setzen der Berechtigungen für die dconf-Datenbank
      command: chmod 600 /etc/dconf/db/local
      when: dconf_permissions.stdout.find('local') != -1

    - name: Setzen der Berechtigungen für die dconf-Datenbank site
      command: chmod 600 /etc/dconf/db/site
      when: dconf_permissions.stdout.find('site') != -1

    - name: Kopieren der dconf-Konfigurationsdatei
      copy:
        src: data/etc/dconf/db/local.d/00-power-settings
        dest: /etc/dconf/db/local.d/00-power-settings

    - name: Zurücksetzen der Benutzereinstellungen für power
      command: dconf reset -f /org/cinnamon/settings-daemon/plugins/power/
      become: no
      ignore_errors: yes  # Ignoriere Fehler, wenn der Benutzer nicht existiert

    - name: Kopieren des Shutdown-Skripts
      copy:
        src: data/etc/local.bin/shutdown-lid.sh
        dest: /usr/local/bin/shutdown-lid.sh
        mode: '0755'

    - name: Kopieren des Setup-Skripts
      copy:
        src: data/etc/local.bin/setup-power-settings.sh
        dest: /usr/local/bin/setup-power-settings.sh
        mode: '0755'

    - name: Kopieren des systemd-Dienstes für das Shutdown-Skript
      copy:
        src: data/etc/systemd/system/lid-shutdown.service
        dest: /etc/systemd/system/lid-shutdown.service

    - name: Kopieren des systemd-Dienstes für das Setup-Skript
      copy:
        src: data/etc/systemd/system/setup-power-settings.service
        dest: /etc/systemd/system/setup-power-settings.service

    - name: Aktivieren des systemd-Dienstes für das Shutdown-Skript
      command: systemctl enable lid-shutdown.service

    - name: Aktivieren des systemd-Dienstes für das Setup-Skript
      command: systemctl enable setup-power-settings.service

  handlers:
    - name: update dconf database
      command: dconf update

  post_tasks:
    - name: Neustart des Systems, wenn Änderungen vorgenommen wurden
      reboot:
      when: logind_conf_update.changed

    - name: Herunterfahren des Systems, wenn keine Änderungen erforderlich sind
      command: shutdown now
      when: not logind_conf_update.changed
