---
- name: Erzwinge die Energieeinstellungen in Cinnamon systemweit
  vars:
    target_group: "{{ target_group | default('INFacerWLAN') }}"
  hosts: "{{ target_group }}"
  remote_user: root
  gather_facts: yes
  tasks:
    - name: Überprüfen, ob die aktuelle logind.conf die richtigen Konfigurationen enthält
      command: grep -E 'HandlePowerKey=poweroff|HandleLidSwitch=ignore|HandleSuspendKey=ignore|HandleHibernateKey=ignore|IdleAction=ignore|PowerKeyIgnoreInhibited=no|LidSwitchIgnoreInhibited=no' /etc/systemd/logind.conf
      register: logind_conf_check
      failed_when: logind_conf_check.rc != 0
      changed_when: false

    - name: Überprüfen, ob die logind.conf vollständig korrekt ist
      set_fact:
        config_correct: "{{ logind_conf_check.stdout_lines | length == 7 }}"

    - name: Erstellen der minimalen logind.conf, wenn die Konfiguration nicht korrekt ist
      copy:
        dest: /etc/systemd/logind.conf
        content: |
          [Login]
          HandlePowerKey=poweroff
          HandleLidSwitch=ignore
          HandleSuspendKey=ignore
          HandleHibernateKey=ignore
          IdleAction=ignore
          PowerKeyIgnoreInhibited=no
          LidSwitchIgnoreInhibited=no
      when: not config_correct

    - name: Überprüfen der dconf-Berechtigungen
      command: ls -altR /etc/dconf
      register: dconf_permissions

    - name: Setzen der Berechtigungen für die dconf-Datenbankdatei 00_power-button
      command: chmod 644 /etc/dconf/db/local.d/00_power-button
      when: dconf_permissions.stdout.find('00_power-button') != -1

    - name: Setzen der Berechtigungen für die dconf-Datenbank
      command: chmod 600 /etc/dconf/db/local
      when: dconf_permissions.stdout.find('local') != -1

    - name: Setzen der Berechtigungen für die dconf-Datenbank site
      command: chmod 600 /etc/dconf/db/site
      when: dconf_permissions.stdout.find('site') != -1

    - name: Erstellen der dconf-Konfigurationsdatei
      copy:
        dest: /etc/dconf/db/local.d/00_power-button
        content: |
          [org/cinnamon/settings-daemon/plugins/power]
          button-power='poweroff'
          lid-close-ac-action='poweroff'
          lid-close-battery-action='poweroff'
      notify: update dconf database

    - name: Zurücksetzen der Benutzereinstellungen für power
      command: dconf reset -f /org/cinnamon/settings-daemon/plugins/power/
      become: no
      ignore_errors: yes  # Ignoriere Fehler, wenn der Benutzer nicht existiert

    - name: Erstellen des Shutdown-Skripts
      copy:
        dest: /usr/local/bin/shutdown-lid.sh
        content: |
          #!/bin/bash
          
          # Überprüfen, ob der Deckel geschlossen ist
          if grep -q closed /proc/acpi/button/lid/LID0/state; then
              # 30 Sekunden warten
              sleep 30
          
              # Überprüfen, ob der Deckel während der Wartezeit geöffnet wurde
              if grep -q open /proc/acpi/button/lid/LID0/state; then
                  exit 0
              fi
          
              # Andernfalls herunterfahren
              shutdown now
          fi
        mode: '0755'
      when: not config_correct

    - name: Erstellen des systemd-Dienstes für das Shutdown-Skript
      copy:
        dest: /etc/systemd/system/lid-shutdown.service
        content: |
          [Unit]
          Description=Shutdown on lid close
          
          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/shutdown-lid.sh
          
          [Install]
          WantedBy=suspend.target
      when: not config_correct

    - name: Aktivieren des systemd-Dienstes
      command: systemctl enable lid-shutdown.service
      when: not config_correct

    - name: Neustart des Systems
      reboot:
      when: not config_correct

    - name: Herunterfahren des Systems, wenn keine Änderungen erforderlich sind
      command: shutdown now
      when: config_correct

    - name: Sicherstellen, dass die dconf-Datenbank aktualisiert wird
      command: dconf update

    - name: Setzen der gsettings für den Netzschalter auf "poweroff"
      command: gsettings set org.cinnamon.settings-daemon.plugins.power button-power 'poweroff'
      become: no
      ignore_errors: yes  # Ignoriere Fehler, wenn der Benutzer nicht existiert

    - name: Setzen der gsettings für das Schließen des Deckels (AC)
      command: gsettings set org.cinnamon.settings-daemon.plugins.power lid-close-ac-action 'poweroff'
      become: no
      ignore_errors: yes  # Ignoriere Fehler, wenn der Benutzer nicht existiert

    - name: Setzen der gsettings für das Schließen des Deckels (Batterie)
      command: gsettings set org.cinnamon.settings-daemon.plugins.power lid-close-battery-action 'poweroff'
      become: no
      ignore_errors: yes  # Ignoriere Fehler, wenn der Benutzer nicht existiert

  handlers:
    - name: update dconf database
      command: dconf update

