---
- name: Dateien vom Desktop des Benutzers auf den lokalen Rechner kopieren
  hosts: INFacerWLAN
  remote_user: root
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  tasks:
    - name: Bestimme den aktuell angemeldeten Benutzer
      shell: who | awk '{print $1}' | grep -v root | sort | uniq
      register: logged_in_users

    - name: Setze den Desktop-Benutzer (erster Benutzer in der Liste)
      set_fact:
        desktop_user: "{{ logged_in_users.stdout_lines[0] }}"

    - name: Erstelle ein Verzeichnis auf dem lokalen Rechner
      local_action: 
        module: file
        path: "/home/mlo/Dokumente/02_schule/00_SJ2024-25/10_Informatik/INF11BC/2024-12-05/{{ inventory_hostname }}"
        state: directory

    - name: Synchronisiere Dateien vom Desktop des aktuell angemeldeten Benutzers auf den lokalen Rechner
      synchronize:
        mode: pull
        src: "/tmp/{{ desktop_user }}/Schreibtisch/"
        dest: "/home/mlo/Dokumente/02_schule/00_SJ2024-25/10_Informatik/INF11BC/2024-12-05/{{ inventory_hostname }}/"

