---
- name: Greenfoot
  vars:
    target_group: "{{ target_group | default('INFacerWLAN') }}"
  hosts: "{{ target_group }}"
  remote_user: root
  tasks:
  - name: Install greenfoot from the internet
    apt:
     deb: https://www.greenfoot.org/download/files/Greenfoot-linux-382.deb

