---
- hosts: INFacerWLAN
  remote_user: root
  tasks:
  - name: Run the equivalent of "apt-get update" as a separate step
    apt:
     update_cache: yes
  - name: Installiere die Programme! 
    apt:
     name: "{{ packages }}"
    vars:
     packages:
     - python3-pip
     - python3-setuptools
     - python3-dev
     - python3-pyqt5
     - python3-pyqt5.qsci
     - python3-pyqt5.qtserialport
     - thonny
     - eog
     - eog-plugins
