---
- name: Dateien auf Desktop übertragen
  hosts: INFacerWLAN
  remote_user: root
  environment:
    ANSIBLE_HOST_KEY_CHECKING: "False"
  tasks:
    - name: Bestimme den aktuell angemeldeten Benutzer
      shell: who | awk '{print $1}' | grep -v root | sort | uniq
      register: logged_in_users

    - name: Setze den Desktop-Benutzer (erster Benutzer in der Liste)
      set_fact:
        desktop_user: "{{ logged_in_users.stdout_lines[0] }}"

    - name: Bestimme das Home-Verzeichnis des aktuell angemeldeten Benutzers
      command: echo $HOME
      register: home_directory
      environment:
        HOME: "/tmp/{{ desktop_user }}"

    - name: Überprüfe, ob der Zielordner auf dem Desktop existiert
      file:
        path: "/tmp/{{ desktop_user }}/Schreibtisch/klausur"
        state: directory
      register: target_directory

    - name: Übertrage den Inhalt des "klausur" Ordners auf den Desktop des aktuell angemeldeten Benutzers
      synchronize:
        src: "./data/klausur/"  # Pfad zum Quellordner relativ zum Playbook
        dest: "/tmp/{{ desktop_user }}/Schreibtisch/klausur/"  # Zielordner auf dem Desktop des Benutzers
        mode: push

    - name: Ändere den Besitzer des Zielordners und dessen Inhalt
      file:
        path: "/tmp/{{ desktop_user }}/Schreibtisch/klausur"
        owner: "{{ desktop_user }}"
        group: "{{ desktop_user }}"
        state: directory
        recurse: yes
